-- Patogh V14 - Timeline Social Features (staging-ready hardened migration)
-- Scope: comments, saved posts, shares and V14 feed RPCs.
-- Safety: does NOT modify or replace V12 timeline RPCs.
-- Target for first execution: Staging only (project ref sxglkafhprigkeqdtanr).

-- ---------------------------------------------------------------------------
-- TABLES
-- ---------------------------------------------------------------------------

create table if not exists public.timeline_comments (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.timeline_posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null default 'کاربر پاتوق',
  text text not null check (char_length(text) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index if not exists timeline_comments_post_created_idx
  on public.timeline_comments(post_id, created_at, id);

create table if not exists public.timeline_saved_posts (
  post_id uuid not null references public.timeline_posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(post_id, user_id)
);

create index if not exists timeline_saved_posts_user_idx
  on public.timeline_saved_posts(user_id, created_at desc);

create table if not exists public.timeline_shares (
  id bigint generated by default as identity primary key,
  post_id uuid not null references public.timeline_posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists timeline_shares_post_idx
  on public.timeline_shares(post_id);

create index if not exists timeline_shares_user_idx
  on public.timeline_shares(user_id, created_at desc);

-- If a partial/manual V14 install created duplicate share rows, normalize them
-- before enforcing one logical share per user/post.
delete from public.timeline_shares newer
using public.timeline_shares older
where newer.post_id = older.post_id
  and newer.user_id = older.user_id
  and newer.id > older.id;

create unique index if not exists timeline_shares_post_user_uidx
  on public.timeline_shares(post_id, user_id);

-- ---------------------------------------------------------------------------
-- RLS: defense in depth. Client table privileges are revoked below, so all
-- V14 mutations go through the RPCs in this migration.
-- ---------------------------------------------------------------------------

alter table public.timeline_comments enable row level security;
alter table public.timeline_saved_posts enable row level security;
alter table public.timeline_shares enable row level security;

drop policy if exists timeline_comments_read on public.timeline_comments;
create policy timeline_comments_read
on public.timeline_comments
for select
to authenticated
using (
  auth.uid() is not null
  and exists (
    select 1
    from public.timeline_posts p
    where p.id = timeline_comments.post_id
      and not exists (
        select 1
        from public.user_blocks b
        where
          (b.blocker_id = auth.uid() and b.blocked_id = p.user_id)
          or
          (b.blocker_id = p.user_id and b.blocked_id = auth.uid())
      )
  )
  and not exists (
    select 1
    from public.user_blocks b
    where
      (b.blocker_id = auth.uid() and b.blocked_id = timeline_comments.user_id)
      or
      (b.blocker_id = timeline_comments.user_id and b.blocked_id = auth.uid())
  )
);

drop policy if exists timeline_comments_insert on public.timeline_comments;
create policy timeline_comments_insert
on public.timeline_comments
for insert
to authenticated
with check (
  auth.uid() is not null
  and user_id = auth.uid()
  and exists (
    select 1
    from public.timeline_posts p
    where p.id = timeline_comments.post_id
      and not exists (
        select 1
        from public.user_blocks b
        where
          (b.blocker_id = auth.uid() and b.blocked_id = p.user_id)
          or
          (b.blocker_id = p.user_id and b.blocked_id = auth.uid())
      )
  )
);

drop policy if exists timeline_comments_delete on public.timeline_comments;
create policy timeline_comments_delete
on public.timeline_comments
for delete
to authenticated
using (user_id = auth.uid());

drop policy if exists timeline_saved_posts_read on public.timeline_saved_posts;
create policy timeline_saved_posts_read
on public.timeline_saved_posts
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists timeline_saved_posts_insert on public.timeline_saved_posts;
create policy timeline_saved_posts_insert
on public.timeline_saved_posts
for insert
to authenticated
with check (
  auth.uid() is not null
  and user_id = auth.uid()
  and exists (
    select 1
    from public.timeline_posts p
    where p.id = timeline_saved_posts.post_id
      and not exists (
        select 1
        from public.user_blocks b
        where
          (b.blocker_id = auth.uid() and b.blocked_id = p.user_id)
          or
          (b.blocker_id = p.user_id and b.blocked_id = auth.uid())
      )
  )
);

drop policy if exists timeline_saved_posts_delete on public.timeline_saved_posts;
create policy timeline_saved_posts_delete
on public.timeline_saved_posts
for delete
to authenticated
using (user_id = auth.uid());

drop policy if exists timeline_shares_read on public.timeline_shares;
create policy timeline_shares_read
on public.timeline_shares
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists timeline_shares_insert on public.timeline_shares;
create policy timeline_shares_insert
on public.timeline_shares
for insert
to authenticated
with check (
  auth.uid() is not null
  and user_id = auth.uid()
  and exists (
    select 1
    from public.timeline_posts p
    where p.id = timeline_shares.post_id
      and not exists (
        select 1
        from public.user_blocks b
        where
          (b.blocker_id = auth.uid() and b.blocked_id = p.user_id)
          or
          (b.blocker_id = p.user_id and b.blocked_id = auth.uid())
      )
  )
);

-- ---------------------------------------------------------------------------
-- DIRECT TABLE ACCESS
-- ---------------------------------------------------------------------------
-- RPC-only client contract for the new V14 tables. This prevents direct table
-- INSERT/DELETE from bypassing the RPC post-visibility/block checks.

revoke all on table public.timeline_comments from public, anon, authenticated;
revoke all on table public.timeline_saved_posts from public, anon, authenticated;
revoke all on table public.timeline_shares from public, anon, authenticated;

-- Do not expose the identity sequence used by timeline_shares to clients.
do $block$
declare
  v_seq text;
begin
  v_seq := pg_catalog.pg_get_serial_sequence('public.timeline_shares', 'id');
  if v_seq is not null then
    execute pg_catalog.format(
      'revoke all on sequence %s from public, anon, authenticated',
      v_seq::regclass
    );
  end if;
end
$block$;

-- ---------------------------------------------------------------------------
-- SAVE / UNSAVE
-- ---------------------------------------------------------------------------

create or replace function public.toggle_timeline_save_v14(p_post_id uuid)
returns boolean
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is null then
    raise exception 'authentication required';
  end if;

  -- Serialize toggles for this exact user/post pair. Hash collisions only cause
  -- harmless extra serialization; they cannot grant access or corrupt data.
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtext(v_uid::text),
    pg_catalog.hashtext(p_post_id::text)
  );

  if not exists (
    select 1
    from public.timeline_posts p
    where p.id = p_post_id
      and not exists (
        select 1
        from public.user_blocks b
        where
          (b.blocker_id = v_uid and b.blocked_id = p.user_id)
          or
          (b.blocker_id = p.user_id and b.blocked_id = v_uid)
      )
  ) then
    raise exception 'post not available';
  end if;

  if exists (
    select 1
    from public.timeline_saved_posts sp
    where sp.post_id = p_post_id
      and sp.user_id = v_uid
  ) then
    delete from public.timeline_saved_posts
    where post_id = p_post_id
      and user_id = v_uid;
    return false;
  end if;

  insert into public.timeline_saved_posts(post_id, user_id)
  values (p_post_id, v_uid);

  return true;
end;
$$;

-- ---------------------------------------------------------------------------
-- ADD COMMENT
-- ---------------------------------------------------------------------------
-- p_author_name is intentionally retained only for RPC signature compatibility.
-- The stored display name is derived from public.profiles, never trusted from
-- the client-provided argument.

create or replace function public.add_timeline_comment_v14(
  p_post_id uuid,
  p_text text,
  p_author_name text default 'کاربر پاتوق'
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_uid uuid := auth.uid();
  v_id uuid;
  v_text text;
  v_author_name text;
begin
  if v_uid is null then
    raise exception 'authentication required';
  end if;

  if not exists (
    select 1
    from public.timeline_posts p
    where p.id = p_post_id
      and not exists (
        select 1
        from public.user_blocks b
        where
          (b.blocker_id = v_uid and b.blocked_id = p.user_id)
          or
          (b.blocker_id = p.user_id and b.blocked_id = v_uid)
      )
  ) then
    raise exception 'post not available';
  end if;

  v_text := pg_catalog.btrim(coalesce(p_text, ''));

  if pg_catalog.char_length(v_text) < 1
     or pg_catalog.char_length(v_text) > 2000 then
    raise exception 'invalid comment length';
  end if;

  select pg_catalog.left(
           coalesce(
             nullif(pg_catalog.btrim(p.name), ''),
             'کاربر پاتوق'
           ),
           120
         )
    into v_author_name
  from public.profiles p
  where p.id = v_uid;

  v_author_name := coalesce(v_author_name, 'کاربر پاتوق');

  insert into public.timeline_comments(
    post_id,
    user_id,
    author_name,
    text
  )
  values (
    p_post_id,
    v_uid,
    v_author_name,
    v_text
  )
  returning id into v_id;

  return v_id;
end;
$$;

-- ---------------------------------------------------------------------------
-- RECORD SHARE
-- ---------------------------------------------------------------------------
-- One logical share row per user/post. Repeated calls return the same row id
-- and therefore do not inflate shares_count.

create or replace function public.record_timeline_share_v14(p_post_id uuid)
returns bigint
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_uid uuid := auth.uid();
  v_id bigint;
begin
  if v_uid is null then
    raise exception 'authentication required';
  end if;

  if not exists (
    select 1
    from public.timeline_posts p
    where p.id = p_post_id
      and not exists (
        select 1
        from public.user_blocks b
        where
          (b.blocker_id = v_uid and b.blocked_id = p.user_id)
          or
          (b.blocker_id = p.user_id and b.blocked_id = v_uid)
      )
  ) then
    raise exception 'post not available';
  end if;

  insert into public.timeline_shares(post_id, user_id)
  values (p_post_id, v_uid)
  on conflict (post_id, user_id) do nothing
  returning id into v_id;

  if v_id is null then
    select s.id
      into v_id
    from public.timeline_shares s
    where s.post_id = p_post_id
      and s.user_id = v_uid;
  end if;

  return v_id;
end;
$$;

-- ---------------------------------------------------------------------------
-- COMMENTS LIST
-- ---------------------------------------------------------------------------

create or replace function public.list_timeline_comments_v14(p_post_id uuid)
returns setof jsonb
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select pg_catalog.jsonb_build_object(
    'id', c.id,
    'post_id', c.post_id,
    'user_id', c.user_id,
    'author_name', c.author_name,
    'text', c.text,
    'created_at', c.created_at
  )
  from public.timeline_comments c
  where c.post_id = p_post_id
    and auth.uid() is not null
    -- The caller must be allowed to see the post itself.
    and exists (
      select 1
      from public.timeline_posts p
      where p.id = p_post_id
        and not exists (
          select 1
          from public.user_blocks b
          where
            (b.blocker_id = auth.uid() and b.blocked_id = p.user_id)
            or
            (b.blocker_id = p.user_id and b.blocked_id = auth.uid())
        )
    )
    -- Also hide comments whose own author is mutually blocked with the caller.
    and not exists (
      select 1
      from public.user_blocks b
      where
        (b.blocker_id = auth.uid() and b.blocked_id = c.user_id)
        or
        (b.blocker_id = c.user_id and b.blocked_id = auth.uid())
    )
  order by c.created_at asc, c.id asc;
$$;

-- ---------------------------------------------------------------------------
-- V14 FEED
-- ---------------------------------------------------------------------------
-- V12 list_timeline_feed_v12() is deliberately left untouched.

create or replace function public.list_timeline_feed_v14()
returns setof jsonb
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select pg_catalog.jsonb_build_object(
    'id', p.id,
    'user_id', p.user_id,
    'author_name', p.author_name,
    'role_label', p.role_label,
    'event_title', p.event_title,
    'event_id', p.event_id,
    'text', p.text,
    'created_at', p.created_at,

    'likes_count',
      (
        select pg_catalog.count(*)
        from public.timeline_likes l
        where l.post_id = p.id
      ),

    'liked_by_me',
      exists (
        select 1
        from public.timeline_likes l
        where l.post_id = p.id
          and l.user_id = auth.uid()
      ),

    -- Count only comments the current viewer can actually receive from the
    -- comments RPC; this prevents a hidden blocked comment from inflating UI.
    'comments_count',
      (
        select pg_catalog.count(*)
        from public.timeline_comments c
        where c.post_id = p.id
          and not exists (
            select 1
            from public.user_blocks b
            where
              (b.blocker_id = auth.uid() and b.blocked_id = c.user_id)
              or
              (b.blocker_id = c.user_id and b.blocked_id = auth.uid())
          )
      ),

    'shares_count',
      (
        select pg_catalog.count(*)
        from public.timeline_shares s
        where s.post_id = p.id
      ),

    'saved_by_me',
      exists (
        select 1
        from public.timeline_saved_posts sp
        where sp.post_id = p.id
          and sp.user_id = auth.uid()
      ),

    'media',
      coalesce(
        (
          select pg_catalog.jsonb_agg(
            pg_catalog.jsonb_build_object(
              'id', m.id,
              'media_type', m.media_type,
              'mime_type', m.mime_type,
              'size_bytes', m.size_bytes,
              'duration_ms', m.duration_ms,
              'storage_path', m.storage_path
            )
            order by pm.sort_order
          )
          from public.timeline_post_media pm
          join public.media_assets m
            on m.id = pm.media_id
          where pm.post_id = p.id
            and m.status = 'approved'
        ),
        '[]'::jsonb
      )
  )
  from public.timeline_posts p
  where auth.uid() is not null
    and not exists (
      select 1
      from public.user_blocks b
      where
        (b.blocker_id = auth.uid() and b.blocked_id = p.user_id)
        or
        (b.blocker_id = p.user_id and b.blocked_id = auth.uid())
    )
  order by p.created_at desc, p.id desc
  limit 100;
$$;

-- ---------------------------------------------------------------------------
-- FUNCTION PRIVILEGES
-- ---------------------------------------------------------------------------
-- CREATE FUNCTION grants EXECUTE to PUBLIC by default, so explicitly close it
-- and expose only the authenticated RPC contract.

revoke all on function public.toggle_timeline_save_v14(uuid) from public, anon;
revoke all on function public.add_timeline_comment_v14(uuid, text, text) from public, anon;
revoke all on function public.record_timeline_share_v14(uuid) from public, anon;
revoke all on function public.list_timeline_comments_v14(uuid) from public, anon;
revoke all on function public.list_timeline_feed_v14() from public, anon;

grant execute on function public.toggle_timeline_save_v14(uuid) to authenticated;
grant execute on function public.add_timeline_comment_v14(uuid, text, text) to authenticated;
grant execute on function public.record_timeline_share_v14(uuid) to authenticated;
grant execute on function public.list_timeline_comments_v14(uuid) to authenticated;
grant execute on function public.list_timeline_feed_v14() to authenticated;
