-- Patogh production schema for Supabase/Postgres

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  phone text,
  name text not null default 'کاربر پاتوق',
  age int,
  city text not null default 'مشهد',
  interests text[] not null default '{}',
  show_age boolean not null default true,
  allow_chat boolean not null default true,
  role text not null default 'user'
    check (role in ('user','host','admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.patogh_events (
  id text primary key,
  host_id uuid references auth.users(id) on delete set null,
  category_id text not null,
  title text not null,
  subtitle text not null default '',
  date_label text not null default '',
  time_label text not null default '',
  area text not null default 'مشهد',
  exact_location_note text not null default '',
  price bigint not null default 0,
  capacity int not null default 6,
  reserved_count int not null default 0,
  women_only boolean not null default false,
  discounted boolean not null default false,
  discount_percent int not null default 0,
  description text not null default '',
  participants text[] not null default '{}',
  tags text[] not null default '{}',
  published boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.reservations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  event_id text not null references public.patogh_events(id) on delete cascade,
  status text not null default 'reserved'
    check (status in ('reserved','confirmed','waitlist','cancelled')),
  payment_status text not null default 'unpaid'
    check (payment_status in ('unpaid','pending','paid','failed','refunded')),
  amount bigint not null default 0,
  created_at timestamptz not null default now(),
  unique(user_id, event_id)
);

create table if not exists public.favorites (
  user_id uuid not null references auth.users(id) on delete cascade,
  event_id text not null references public.patogh_events(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(user_id, event_id)
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  room_id text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  text text not null check (char_length(text) between 1 and 4000),
  created_at timestamptz not null default now()
);

create table if not exists public.device_tokens (
  token text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  platform text not null default 'web',
  updated_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  body text not null,
  data jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.patogh_events enable row level security;
alter table public.reservations enable row level security;
alter table public.favorites enable row level security;
alter table public.chat_messages enable row level security;
alter table public.device_tokens enable row level security;
alter table public.notifications enable row level security;

drop policy if exists "profiles_self_select" on public.profiles;
create policy "profiles_self_select"
on public.profiles for select
using (auth.uid() = id);

drop policy if exists "profiles_self_write" on public.profiles;
create policy "profiles_self_write"
on public.profiles for all
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "events_public_read" on public.patogh_events;
create policy "events_public_read"
on public.patogh_events for select
using (published = true);

drop policy if exists "events_host_insert" on public.patogh_events;
create policy "events_host_insert"
on public.patogh_events for insert
with check (
  auth.uid() = host_id
  and exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and p.role in ('host','admin')
  )
);

drop policy if exists "events_host_update" on public.patogh_events;
create policy "events_host_update"
on public.patogh_events for update
using (
  auth.uid() = host_id
  or exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

drop policy if exists "reservations_self" on public.reservations;
create policy "reservations_self"
on public.reservations for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "favorites_self" on public.favorites;
create policy "favorites_self"
on public.favorites for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "chat_authenticated_read" on public.chat_messages;
create policy "chat_authenticated_read"
on public.chat_messages for select
using (auth.role() = 'authenticated');

drop policy if exists "chat_self_insert" on public.chat_messages;
create policy "chat_self_insert"
on public.chat_messages for insert
with check (auth.uid() = user_id);

drop policy if exists "tokens_self" on public.device_tokens;
create policy "tokens_self"
on public.device_tokens for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "notifications_self" on public.notifications;
create policy "notifications_self"
on public.notifications for select
using (auth.uid() = user_id);

create or replace function public.reserve_event(
  p_event_id text,
  p_waitlist_only boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_capacity int;
  v_reserved int;
  v_status text;
begin
  if v_user is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  select capacity
  into v_capacity
  from public.patogh_events
  where id = p_event_id
  for update;

  if v_capacity is null then
    raise exception 'EVENT_NOT_FOUND';
  end if;

  select count(*)
  into v_reserved
  from public.reservations
  where event_id = p_event_id
    and status in ('reserved','confirmed');

  if p_waitlist_only or v_reserved >= v_capacity then
    v_status := 'waitlist';
  else
    v_status := 'reserved';
  end if;

  insert into public.reservations (
    user_id,
    event_id,
    status
  )
  values (
    v_user,
    p_event_id,
    v_status
  )
  on conflict (user_id, event_id)
  do update set status = excluded.status;

  update public.patogh_events
  set reserved_count = (
    select count(*)
    from public.reservations
    where event_id = p_event_id
      and status in ('reserved','confirmed')
  )
  where id = p_event_id;

  return jsonb_build_object('status', v_status);
end;
$$;

grant execute on function public.reserve_event(text, boolean)
to authenticated;
