name: Test Android Keystore

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-keystore:
    runs-on: ubuntu-latest

    env:
      ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Decode keystore
        run: |
          echo "SECRET LENGTH:"
          echo -n "$ANDROID_KEYSTORE_BASE64" | wc -c

          echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > test-release.jks

          echo "FILE SIZE:"
          ls -lh test-release.jks

      - name: Check keystore
        run: |
          keytool -list -v \
          -keystore test-release.jks \
          -storepass "$ANDROID_STORE_PASSWORD"
