name: Test Secret Exists

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      TEST_SECRET: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

    steps:
      - name: Check secret length
        shell: bash
        run: |
          echo "START"
          echo -n "$TEST_SECRET" | wc -c
          echo "END"